- name: Ensure tig data directory exists
  become: False
  file:
    path: ~/.local/share/tig
    state: directory

- name: Add user to groups
  user:
    append: True
    name: "{{ ansible_user }}"
    groups: docker,input,vboxusers,wireshark
    shell: /bin/zsh

- name: Install ruby packages
  become: False
  gem:
    name: "{{ item }}"
    user_install: True
  with_items: "{{ ruby_packages }}"

- name: Install pip packages
  become: False
  pip:
    name: "{{ item }}"
    extra_args: --user
  with_items: "{{ python_packages }}"

- name: Install npm packages
  become: False
  npm:
    name: "{{ item }}"
    global: True
  with_items: "{{ npm_packages }}"

- name: Autostart libinput gestures
  become: False
  command: libinput-gestures-setup autostart
  args:
    creates: ~/.config/autostart/libinput-gestures.desktop

- name: Autostart disable-panel-shadow
  become: False
  copy:
    dest: ~/.config/autostart/disable-panel-shadow.desktop
    src: files/disable-panel-shadow.desktop
