#!/bin/bash

set -xeuo pipefail
IFS=$'\n\t'

_GIT_DIR="$(git rev-parse --git-dir)"

_CTAGS_TEMP_FILE="$_GIT_DIR/$$.tags"
_CTAGS_TARGET_FILE="$_GIT_DIR/tags"

export GTAGSCONF=/usr/local/share/gtags/gtags.conf
export GTAGSLABEL=ctags
_GTAGS_TARGET_DIR="$(git rev-parse --show-toplevel)"
_GTAGS_TEMP_DIR="$_GIT_DIR/$$_GTAGS"

function cleanUp() {
  rm -f "$_CTAGS_TEMP_FILE"
  rm -rf "$_GTAGS_TEMP_DIR"
}

trap cleanUp EXIT

# ctags
ctags --tag-relative -f "$_CTAGS_TEMP_FILE"
mv "$_CTAGS_TEMP_FILE" "$_CTAGS_TARGET_FILE"

# ggtags
mkdir "$_GTAGS_TEMP_DIR"
gtags "$_GTAGS_TEMP_DIR"
mv "$_GTAGS_TEMP_DIR"/* "$_GTAGS_TARGET_DIR"
rm -rf "$_GTAGS_TEMP_DIR"
