#!/bin/bash

set -e

function cleanUp() {
  rm -f "$dir/$$.tags"
  rm -f "$dir/$$.TAGS"
}

dir="$(git rev-parse --git-dir)"
trap cleanUp EXIT
git ls-files | ctags --tag-relative -L - -f"$dir/$$.tags"
git ls-files | ctags -e --tag-relative -L - -f"$dir/$$.TAGS"
mv "$dir/$$.tags" "$dir/tags" # ctags standard file
mv "$dir/$$.TAGS" "$dir/TAGS" # Emacs tags file
