" vim: set foldlevel=0 foldmethod=marker:

set nocompatible
let mapleader = ","

" Vimscripts {{{
source ~/.vim/bundles.vim
source ~/.vim/keymaps.vim
runtime macros/matchit.vim " match the opening/closign html tag when pressing '%'
" }}}

" Vim options {{{
filetype plugin indent on
syntax on
set encoding=utf-8
set number
set relativenumber
set ignorecase
set smartcase
set infercase
set hlsearch
set incsearch
set smartindent
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set backspace=indent,eol,start
set wildmenu
set wildmode=full
set mouse=a
set nowrap
set shiftround
set laststatus=2
set nobackup
set noswapfile
set undodir=~/.vim/tmp/undo//
set undofile
set undolevels=1000 "maximum number of changes that can be undone
set undoreload=10000 "maximum number lines to save for undo on a buffer reload
set dictionary=/usr/share/dict/words
set foldmethod=syntax
set nofoldenable
set history=1000
set scrolloff=3 " Leave some ground while scrolling
set background=dark
set shortmess+=c " Quiet completions
set splitright
set updatetime=250
set colorcolumn=80
set termguicolors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
colorscheme badwolf
" }}}

" Highlight {{{
highlight OverLength ctermbg=red ctermfg=white guibg=#592929

" Marks the 81st column of lines wider than 80 characters
function! ShowOverLength()
  if !exists('b:over_length_match')
    let b:over_length_match = matchadd('OverLength', '\v%81v\ze(.+)', 100)
  endif
endfunction

function! HideOverLength()
  if exists('b:over_length_match')
    call matchdelete(b:over_length_match)
    unlet b:over_length_match
  endif
endfunction

command HideOverLength call HideOverLength()
command ShowOverLength call ShowOverLength()
" }}}

augroup markdown " {{{
  autocmd!

  " Set syntax highlighting for specific file types
  autocmd BufRead,BufNewFile *.md set filetype=markdown
  " Enable spellchecking for Markdown
  autocmd FileType markdown setlocal spell
  " Automatically wrap at 80 characters for Markdown
  autocmd BufRead,BufNewFile *.md setlocal textwidth=80
augroup END " }}}

augroup git " {{{
  autocmd!

  " Automatically wrap at 72 characters and spell check git commit messages
  autocmd FileType gitcommit setlocal textwidth=72
  autocmd FileType gitcommit setlocal spell
  " Automatically closes Fugitive.vim buffers when leaving them
  autocmd BufReadPost fugitive://* set bufhidden=delete
augroup END
" }}}

" General auto commands {{{
augroup vimrcEx
  autocmd!
  " When editing a file, always jump to the last known cursor position.
  " Don't do it for commit messages, when the position is invalid, or when
  " inside an event handler (happens when dropping a file on gvim).
  autocmd BufReadPost *
        \ if &ft != 'gitcommit' && line("'\"") > 0 && line("'\"") <= line("$") |
        \ exe "normal g`\"" |
        \ endif
  " Allow stylesheets and html to autocomplete hyphenated words
  autocmd FileType html,css,scss,sass setlocal iskeyword+=-
  " Remove any trailing whitespace before saving
  autocmd BufWrite * :FixWhitespace
  " Resize splits when the window is resized
  autocmd VimResized * :wincmd =
  " Treat ? as part of names in Ruby
  autocmd FileType ruby setlocal iskeyword+=?
augroup END
" }}}

" Ag as grep {{{
if executable('ag')
  set grepprg=ag\ --nogroup\ --nocolor\ --smart-case
end
" }}}

" Ale {{{
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_sign_column_always = 1
let g:ale_sign_error = '✗'
let g:ale_sign_warning = '⚠'
let g:ale_statusline_format = ['✗ %d', '⚠ %d', '']
highlight link ALEErrorSign errormsg
highlight link ALEWarningSign question
" }}}

" Netrw {{{
let g:netrw_localrmdir='rm -r'
" }}}

" Vim instant markdown {{{
let g:instant_markdown_autostart = 0
" }}}

" Lightline {{{
function! LightlineFilename()
  let filename = ""
  if &readonly && &filetype != "help"
    let filename .= " "
  endif

  let filename .= (expand('%:t') != '' ? expand('%:t') : '[No Name]')

  if &modified && &filetype != "help"
    let filename .= " +"
  endif

  return filename
endfunction

function! LightlineFugitive()
  if exists("*fugitive#head")
    let branch = fugitive#head()
    return branch !=# '' ? ' '.branch : ''
  endif
  return ''
endfunction

let g:lightline = {
  \ 'active': {
  \   'left': [ [ 'mode', 'paste' ], [ 'fugitive', 'ale', 'filename' ] ]
  \ },
  \ 'component': {
  \   'filename': '%{LightlineFilename()}',
  \   'fugitive': '%{LightlineFugitive()}',
  \   'ale': '%{ALEGetStatusLine()}'
  \ },
  \ 'component_visible_condition': {
  \   'fugitive': '(exists("*fugitive#head") && ""!=fugitive#head())',
  \   'ale': "ALEGetStatusLine() != ''"
  \ },
  \ 'separator': { 'left': '', 'right': '' },
  \ 'subseparator': { 'left': '', 'right': '' }
  \ }
let g:buftabline_numbers = 1
let g:buftabline_indicators = 1
let g:buftabline_separators = 1
let g:lightline.colorscheme = 'Tomorrow_Night'
" }}}

" Switch {{{
autocmd FileType ruby let b:switch_custom_definitions =
  \ [
  \   {
  \     'validates_\(\w\+\)_of\s\+\(:\w\+\)': 'validates \2, \1: true',
  \     'validates\s\+:\(\w\+\),\s\+\(\w\+\):\s\+true':     'validates_\2_of :\1',
  \   },
  \ ]
" }}}

" Vim test {{{
let g:test#strategy = 'vtr'
" }}}

" Localvimrc  {{{
let g:localvimrc_persistent = 1
let g:localvimrc_sandbox = 0
" }}}

" FZF {{{
" Return a list with all open buffers
function! s:buflist()
  redir => ls
  silent ls
  redir END
  return split(ls, '\n')
endfunction

" Handles a MRU search in FZF
function! s:bufopen(e)
  " Exit if no file was picked
  if len(a:e) < 2 | return | endif

  " Fzf sends two lines the first with the key combination used to pick
  " a file and the second with the matched line
  let [key, buffer_line] = a:e[0:1]
  " Extract the buffer number from the matched line
  let buffer_number = matchstr(buffer_line, '^[ 0-9]*')
  " Pick the appropriate command based on the key combination used
  let cmd = get({
        \ 'ctrl-x': 'sbuffer',
        \ 'ctrl-v': 'vertical sbuffer',
        \ 'ctrl-t': 'tabnew | buffer '
        \ }, key, 'buffer')
  " Run the picked command with the matched buffer
  execute cmd . buffer_number
endfunction

" Command to list MRU files
command! FZFMru call fzf#run({
      \ 'source': reverse(<sid>buflist()),
      \ 'sink*': function('<sid>bufopen'),
      \ 'options': '--expect=ctrl-t,ctrl-v,ctrl-x',
      \ 'down': len(<sid>buflist()) + 2
      \ })
" }}}

" CtrlSF {{{
let g:ctrlsf_default_root = 'project'
let g:ctrlsf_leading_space = 2
let g:ctrlsf_regex_pattern = 1
" }}}

" Disable standard tComment mappings {{{
let g:tcommentMapLeader1 = ''
let g:tcommentMapLeader2 = ''
" }}}

" Yank Ring {{{
let g:yankring_dot_repeat_yank = 1
let g:yankring_clipboard_monitor = 0
" }}}

" Ultisnips {{{
let g:UltiSnipsUsePythonVersion = 3
" }}}

" YCM {{{
let g:ycm_collect_identifiers_from_tags_files = 1
" }}}

" Gundo {{{
let g:gundo_prefer_python3 = 1
" }}}

" Vim Debug {{{
let g:vdebug_options = {
      \ 'path_maps': {
      \ '/var/www/dc-commerce': '/home/bruno/code/vizir/dc-commerce/www/dc-commerce'
      \ }
      \ }
" }}}

" Denite {{{
call denite#custom#var('file_rec', 'command', ['rg', '--files', '--hidden', '--glob', '!.git'])
call denite#custom#source('file_rec', 'sorters', ['sorter_sublime_multiprocess'])
call denite#custom#map('insert', '<C-n>', 'move_to_next_line')
call denite#custom#map('insert', '<C-p>', 'move_to_prev_line')
call denite#custom#option('default', 'winheight', 10)

hi link deniteMatched Underline
hi link deniteMatchedChar DiffText

augroup filetype_denite
  autocmd!
  autocmd FileType denite call s:denite_keymapping()
augroup END
" }}}

" GitGutter {{{
let g:gitgutter_async = 1
let g:gitgutter_realtime = 1
" }}}

" Auto create dir on save {{{
augroup CreateDir
  au!
  au BufWritePre,FileWritePre * call <SID>CreateAndSaveDirectory()
augroup END

function s:CreateAndSaveDirectory()
  let s:directory = expand('<afile>:p:h')
  if !isdirectory(s:directory)
    call mkdir(s:directory, 'p')
  endif
endfunction
" }}}

" Terraform {{{
let g:terraform_fmt_on_save = 1
" }}}
